version: 2.1
orbs:
  samvera: samvera/circleci-orb@0
jobs:
  bundle_and_test:
    parameters:
      ruby_version:
        type: string
        default: 2.6.3
      rails_version:
        type: string
        default: 5.2.3
      bundler_version:
        type: string
        default: 2.0.1
      ruby_type:
        type: string
        default: ruby
    executor:
      name: 'samvera/ruby'
      ruby_version: << parameters.ruby_version >>
      ruby_type: << parameters.ruby_type >>
    environment:
      RAILS_VERSION: << parameters.rails_version >>
    working_directory: ~/project
    steps:
      - run: sudo apt-get update && sudo apt-get install libgmp-dev

      - samvera/cached_checkout

      - samvera/bundle_for_gem:
          ruby_version: << parameters.ruby_version >>
          bundler_version: << parameters.bundler_version >>
          project: ldp

      - samvera/parallel_rspec

workflows:
  ci:
    jobs:
      - bundle_and_test:
          name: "ruby2-6_rails5-2"
          ruby_version: "2.6.3"
      - bundle_and_test:
          name: "ruby2-5_rails5-2"
          ruby_version: "2.5.5"
      - bundle_and_test:
          name: "ruby2-4_rails5-2"
          ruby_version: "2.4.6"
      - bundle_and_test:
          name: "jruby9-2_rails5-2"
          ruby_version: "9.2.0.0"
          ruby_type: "jruby"
      - bundle_and_test:
          name: "jruby9-1_rails5-2"
          ruby_version: "9.1.17.0"
          ruby_type: "jruby"
      - bundle_and_test:
          name: "ruby2-6_rails5-1"
          ruby_version: "2.6.3"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "ruby2-5_rails5-1"
          ruby_version: "2.5.5"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "ruby2-4_rails5-1"
          ruby_version: "2.4.6"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "jruby9-2_rails5-1"
          ruby_version: "9.2.0.0"
          ruby_type: "jruby"
          rails_version: "5.1.7"
      - bundle_and_test:
          name: "jruby9-1_rails5-1"
          ruby_version: "9.1.17.0"
          ruby_type: "jruby"
          rails_version: "5.1.7"
